apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-simple-pod-with-resource
  labels:
    app: kubernetes-simple-pod-with-resource
spec:
  containers:
  - name: kubernentes-simple-pod-with-resource
    image: arisu1000/simple-container-app:latest
    resources:
      requests:
        cpu: 0.1
        memory: 200M
      limits:
        cpu: 0.5
        memory: 1G
    ports: 
    - containerPort: 8080
