apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-simple-pod-init
  labels:
    app: kubernetes-simple-pod-init
spec:
  initContainers:
  - name: init-myservice
    image: arisu1000/simple-container-app:latest
    command: ['sh', '-c', 'sleep 2; echo helloservice!;']
  - name: init-mydb
    image: arisu1000/simple-container-app:latest
    command: ['sh', '-c', 'sleep 2; echo hellodb!;']
  containers:
  - name: kubernentes-simple-pod-init
    image: arisu1000/simple-container-app:latest
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
